name: 'phase2'

services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    networks:
      - Frontend
  redis:
    image: redis:3.2
    networks:
      - Frontend
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - Frontend
      - Backend
  db:
    image: postgres:9.4
    networks:
      - Backend
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    networks:
      - Backend

networks:
  Frontend:
  Backend:

volumes:
  db-data:
