services:
  catalog-management:
    build:
      context: ./backend/catalog-management
      target: dev
    ports:
      - 8081:8081
    volumes:
      - ./backend/catalog-management:/app:delegated
      - /app/node_modules
