version: '3'
services: 
  webapp: # the build command tells compose it's building this image
    build: # Will build in the current directory 
    context: . 
    dockerfile: whateverthenameis.Dockerfile # by passing a name here you are telling compose to name and tag the built image by this name 
    image: whateverImage:whatevertag 
    ports: - '80:80'
